export const offendersData = [
  {
    id: "1",
    name: "Robert Martinez",
    crime: "Sexual Assault of a Minor",
    convictionDate: "March 15, 2018",
    sentenceLength: "10 years",
    location: "Los Angeles, CA",
    status: "Registered",
    supervision: "Community Supervision",
    riskLevel: "high-risk" as const,
    physicalDescription: {
      height: "5'10\"",
      weight: "185 lbs",
      hair: "Brown",
      eyes: "Hazel",
    },
    restrictions: [
      "Stay 1000 feet away from schools",
      "Stay 500 feet away from parks",
      "No contact with minors",
      "Weekly check-ins with parole officer",
      "Must maintain employment",
    ],
    notes:
      "Subject has a history of grooming behavior. Must report any change of residence immediately. Has completed sex offender treatment program.",
    lastUpdated: "2024-03-01",
  },
  {
    id: "2",
    name: "James Wilson",
    crime: "Child Exploitation",
    convictionDate: "July 22, 2019",
    sentenceLength: "8 years",
    location: "San Francisco, CA",
    status: "Registered",
    supervision: "Community Supervision",
    riskLevel: "high-risk" as const,
    physicalDescription: {
      height: "5'8\"",
      weight: "160 lbs",
      hair: "Black",
      eyes: "Brown",
    },
    restrictions: [
      "No internet access at residence",
      "Stay away from playgrounds",
      "Cannot work with children",
      "Mandatory counseling",
      "Monitored computer use only",
    ],
    notes:
      "Online predator. Subject attempted to evade supervision. Monitor closely for any suspicious online activity. Compliance has been improving.",
    lastUpdated: "2024-02-28",
  },
  {
    id: "3",
    name: "Christopher Lee",
    crime: "Indecent Exposure & Sexual Battery",
    convictionDate: "November 10, 2017",
    sentenceLength: "5 years",
    location: "San Diego, CA",
    status: "Registered",
    supervision: "Community Supervision",
    riskLevel: "medium" as const,
    physicalDescription: {
      height: "5'11\"",
      weight: "175 lbs",
      hair: "Blonde",
      eyes: "Blue",
    },
    restrictions: [
      "Stay 500 feet away from beaches",
      "No contact with victims",
      "Weekly meetings with counselor",
      "Annual polygraph testing",
    ],
    notes: "Subject has maintained steady employment. Compliance has been good. Poses moderate risk to community.",
    lastUpdated: "2024-03-02",
  },
  {
    id: "4",
    name: "David Anderson",
    crime: "Sexual Assault",
    convictionDate: "September 5, 2020",
    sentenceLength: "7 years",
    location: "Sacramento, CA",
    status: "Registered",
    supervision: "Community Supervision",
    riskLevel: "high-risk" as const,
    physicalDescription: {
      height: "6'0\"",
      weight: "200 lbs",
      hair: "Brown",
      eyes: "Brown",
    },
    restrictions: [
      "Avoid areas with high youth concentration",
      "No unsupervised contact with minors",
      "Electronic monitoring required",
      "Bi-weekly check-ins",
    ],
    notes:
      "Subject has shown resistance to treatment. Requires close monitoring. Multiple restraining orders filed by victims.",
    lastUpdated: "2024-02-25",
  },
  {
    id: "5",
    name: "Kevin Thompson",
    crime: "Child Sexual Abuse Material Possession",
    convictionDate: "June 12, 2021",
    sentenceLength: "6 years",
    location: "Oakland, CA",
    status: "Registered",
    supervision: "Probation",
    riskLevel: "high-risk" as const,
    physicalDescription: {
      height: "5'9\"",
      weight: "170 lbs",
      hair: "Dark Brown",
      eyes: "Brown",
    },
    restrictions: [
      "Complete ban on internet access",
      "Device monitoring by authorities",
      "No devices with digital storage",
      "Monthly compliance checks",
    ],
    notes:
      "Internet-based offender. Subject maintains computer access only under supervision. Cooperating with authorities.",
    lastUpdated: "2024-03-03",
  },
]
